export const taxProfiles = {
  'United Arab Emirates': {
    country: 'United Arab Emirates',
    currency: 'AED',
    defaultTaxRate: '5',
    taxName: 'VAT',
    taxAuthority: 'Federal Tax Authority',
    registrationLabel: 'FTA TRN Registration ID',
    sampleRegistration: '100348572900003',
    license: 'DHA-PH-2026-8874',
    phone: '+971 4 555 0199',
    address: 'Office Suite 4B, Health Heights, Downtown Dubai, Dubai, UAE',
    currencyLabel: 'AED (UAE Dirham)',
    noticeTitle: 'UAE VAT Compliance Notice',
    notice: 'For UAE pharmacies, Federal Tax Authority standard VAT is configured at 5% across generic and medical products.',
    taxRates: [
      { value: '5', label: '5% UAE Standard VAT' },
      { value: '0', label: '0% Tax Exempted Items' },
    ],
    invoiceFooter: 'This Tax Invoice is issued in accordance with UAE VAT requirements.',
  },
  'India (Kerala)': {
    country: 'India (Kerala)',
    currency: 'INR',
    defaultTaxRate: '12',
    taxName: 'GST',
    taxAuthority: 'Goods and Services Tax Network',
    registrationLabel: 'GSTIN Registration ID',
    sampleRegistration: '32AABCA1234F1Z5',
    license: 'KL-KKD-2026-PHA-998',
    phone: '+91 90375 07643',
    address: 'First Floor, ABC Complex, Near Bus Stand, Omassery, Calicut, Kerala 673582',
    currencyLabel: 'INR (Indian Rupee)',
    noticeTitle: 'India GST Compliance Notice',
    notice: 'For Indian pharmacies, medicine supplies commonly use GST slabs such as 5%, 12%, or 18%. Kerala billing can show CGST and SGST split equally when required.',
    taxRates: [
      { value: '0', label: '0% Exempted Items' },
      { value: '5', label: '5% Essential / Lifesaving Medicines' },
      { value: '12', label: '12% Standard Medicine GST' },
      { value: '18', label: '18% Supplements & Non-essential Items' },
    ],
    splitTax: {
      enabled: true,
      labels: ['CGST', 'SGST'],
    },
    invoiceFooter: 'This Tax Invoice supports India GST reporting with CGST/SGST split where applicable.',
  },
  'Saudi Arabia': {
    country: 'Saudi Arabia',
    currency: 'SAR',
    defaultTaxRate: '15',
    taxName: 'VAT',
    taxAuthority: 'ZATCA',
    registrationLabel: 'VAT Registration Number',
    sampleRegistration: '300000000000003',
    license: 'SFDA-PH-2026-1001',
    phone: '+966 11 555 0199',
    address: 'Riyadh Pharmacy Branch, Riyadh, Saudi Arabia',
    currencyLabel: 'SAR (Saudi Riyal)',
    noticeTitle: 'Saudi VAT Compliance Notice',
    notice: 'Saudi Arabia VAT can be configured for pharmacy sales using the active ZATCA registration details.',
    taxRates: [
      { value: '15', label: '15% Saudi Standard VAT' },
      { value: '0', label: '0% Zero-rated / Exempted Items' },
    ],
    invoiceFooter: 'This Tax Invoice is configured for Saudi VAT reporting.',
  },
  Oman: {
    country: 'Oman',
    currency: 'OMR',
    defaultTaxRate: '5',
    taxName: 'VAT',
    taxAuthority: 'Oman Tax Authority',
    registrationLabel: 'VAT Registration Number',
    sampleRegistration: 'OM-VAT-1000001',
    license: 'OM-PH-2026-1001',
    phone: '+968 24 555 019',
    address: 'Muscat Pharmacy Branch, Muscat, Oman',
    currencyLabel: 'OMR (Omani Rial)',
    noticeTitle: 'Oman VAT Compliance Notice',
    notice: 'Oman VAT can be configured for pharmacy sales with local registration details.',
    taxRates: [
      { value: '5', label: '5% Oman Standard VAT' },
      { value: '0', label: '0% Exempted Items' },
    ],
    invoiceFooter: 'This Tax Invoice is configured for Oman VAT reporting.',
  },
  Qatar: {
    country: 'Qatar',
    currency: 'QAR',
    defaultTaxRate: '0',
    taxName: 'Tax',
    taxAuthority: 'Qatar General Tax Authority',
    registrationLabel: 'Tax Registration Number',
    sampleRegistration: 'QA-TAX-1000001',
    license: 'QA-PH-2026-1001',
    phone: '+974 44 555 019',
    address: 'Doha Pharmacy Branch, Doha, Qatar',
    currencyLabel: 'QAR (Qatari Riyal)',
    noticeTitle: 'Qatar Tax Configuration Notice',
    notice: 'Qatar tax settings are prepared as a configurable country profile for future VAT or pharmacy tax requirements.',
    taxRates: [
      { value: '0', label: '0% Current Tax / Exempted Items' },
      { value: '5', label: '5% Future VAT Template' },
    ],
    invoiceFooter: 'This Tax Invoice is configured for Qatar tax reporting.',
  },
  Custom: {
    country: 'Custom',
    currency: 'USD',
    defaultTaxRate: '0',
    taxName: 'Tax',
    taxAuthority: 'Custom Tax Authority',
    registrationLabel: 'Tax Registration Number',
    sampleRegistration: 'CUSTOM-TAX-ID',
    license: 'CUSTOM-PH-LICENSE',
    phone: '+1 000 000 0000',
    address: 'Custom pharmacy address',
    currencyLabel: 'Custom currency',
    noticeTitle: 'Custom Country Tax Notice',
    notice: 'Use this profile for any future country. Update currency, tax rate, registration number, and invoice labels before production use.',
    taxRates: [
      { value: '0', label: '0% Tax' },
      { value: '5', label: '5% Tax' },
      { value: '10', label: '10% Tax' },
      { value: '12', label: '12% Tax' },
      { value: '15', label: '15% Tax' },
      { value: '18', label: '18% Tax' },
    ],
    invoiceFooter: 'This Tax Invoice is configured using a custom country tax profile.',
  },
};

export const getTaxProfile = (region) => taxProfiles[region] || taxProfiles['United Arab Emirates'];

export const getTaxProfileOptions = () =>
  Object.entries(taxProfiles).map(([value, profile]) => ({
    value,
    label: `${profile.country} (${profile.defaultTaxRate}% ${profile.taxName})`,
  }));

